### ISSUE TITLE
data-wl-width & height are not applied

### ISSUE THREAD

**Issue by kennytordeur** [layerJS/layerJS#25]
layout.renderFramePosition() checks if width and height are in diff (which they are not) and hence does not set width and height of element

this has been observed in canvas layout, may also apply to other layouts\
\
Originally created at 2016-06-07 15:28:59+00:00 (UTC) by thomashandorf as a(n) major issue.

**Comment by kennytordeur** [comment]
this is related to issue #13 . Currently we don’t render at all if the element already exists in order to save initialization time (this idea still originates from webpgr where (correctly) pre rendered pages are supplied) We need to revise this idea. Here the user will assume if he provides data-wl-width the library will deal with it.

**Comment by thomashandorf** [comment]
don't know whether this still exists.

**Comment by kennytordeur** [comment]
This has been resolved. When you call view.width(true), it will use the (data-)lj-width value. This is called in the renderFramePosition in the different layouts.

The same is true for the height.
