### ISSUE TITLE
position of frames in “canvas” layout via CSS

### ISSUE THREAD

**Issue by kennytordeur** [layerJS/layerJS#26]
it should be possible to position frames in canvas mode though top and left css properties.

the difficulty here is that this needs to be overwritten by the transform later on (or at least compensated)\
\
Originally created at 2016-06-07 14:59:38+00:00 (UTC) by thomashandorf as a(n) major issue.

**Comment by thomashandorf** [comment]
actually the canvas layout doesn't use top & left. it only uses transform. so this should work. It cannot be set through transform though initially

**Comment by kennytordeur** [comment]
Tested it and it works.

You can position frames using top & left in the css in the canvas layout. You can even combine it with the lj-x and lj-y attributes.
