### ISSUE TITLE
isRendered does not work

### ISSUE THREAD

**Issue by kennytordeur** [layerJS/layerJS#27]
in render() isRendered is checked in order to decide if only the changedAttributes will be considered. There is 
1. a spelling error “isRendererd”
2. isRendered is false when the View was initialized with an existing element (hence render() is never called) -> does that make sense or should a pre-rendered element have “isRendered=true”?

This has been observed in GroupView but may apply to other View Classes as well

(currently, after a render (e.g. after changing the data object) all properties will be rendered)\
\
Originally created at 2016-06-07 14:14:51+00:00 (UTC) by thomashandorf as a(n) minor issue.

**Comment by thomashandorf** [comment]
@kennytordeur is this still relevant?
will probably not be relevant anymore after framework split (maybe for the framework but this we will find anyway)
