### ISSUE TITLE
frame height is zero during setup when dimension derived from image

### ISSUE THREAD

**Issue by kennytordeur** [layerJS/layerJS#28]
if a frame has no dimensions defined it will get it’s dimensions from the content. if this is an image of unknown dimension the frame height will be zero when the initial transform is calculated, hence creating a scroller of height zero

this is a minor problem as the frame dimension can be set.

best would be that the transition code reacts to size changes of the frames\
\
Originally created at 2016-06-07 13:06:42+00:00 (UTC) by thomashandorf as a(n) major issue.

**Comment by thomashandorf** [comment]
this is implemented in v0.3
we now listen to size changes regularly
