### ISSUE TITLE
take id as frame name if lj-name is not given

### ISSUE THREAD

**Issue by thomashandorf** [layerJS/layerJS#41]
when a frame has no given lj-name the layer will fail in the constructor as it will try to change to the current frame (which exists) by accessing currentframe.data.attributes.name
if no id is give either it should probably take frame[x] notation where x is the xth frame child

this most likely should be done in parse.

! this issue is on hold, because it will be solved differently after framework split

after the split it will be implemented in special getAttributes function

**Comment by kennytordeur** [comment]
This problem has been resolved in the branch "no-data-object". It has been merged in the master branch.
