### ISSUE TITLE
npm error message doesn't displaying LayerJS as Authur for the user to contact.

### ISSUE THREAD

**Issue by giliyoffe** [layerJS/layerJS#47]
Gili Yoffe Today at 10:33am
 status(23.12.16 - 10:24): Doesnt reproduce 

scenario:
 - downloaded zip from 
https://github.com/layerJS/layerJS
- ran : npm run build

expected result:
 in a case of an error*
the info that is displayed to the user should
indicate the contactable author. 
(reproduced once in the past and if this issue will get a higher priority - the next step would be to search for the specific scenario to reproduce the issue)
 *sideNote: in this case, originally , wasn't expecting an err msg.

Actual result:
issue did not reproduce.
- received err msg that DOES contains layerjs as the Author that the user should contact.

attachments:
npm authur issue cmd log.txt
npm-debug.log as npm-debug.log.changeFileExtensionTo.log
because .log files are not possible to attach.

[npm authur issue cmd log.txt](https://github.com/layerJS/layerJS/files/670565/npm.authur.issue.cmd.log.txt)

[npm-debug.log.changeFileExtensionTo.log.txt](https://github.com/layerJS/layerJS/files/670580/npm-debug.log.changeFileExtensionTo.log.txt)

**Comment by giliyoffe** [comment]
the author reference:

>You can get information on how to open an issue for this project with:
>npm ERR!     npm bugs layerJS
>npm ERR! Or if that isn't available, you can get their info via:
>npm ERR!     npm owner ls layerJS

**Comment by giliyoffe** [comment]
node -v
v6.2.2

**Comment by kennytordeur** [comment]
Did you do a "npm install" before? 
I get the impression that it doesn't know the module rimraf

**Comment by giliyoffe** [comment]
You are right, I didn't.
After I did It ran without any errors.
Thank you

**Comment by thomashandorf** [comment]
may be difficult to do on the npm side. Added a comment to console on browser
