### ISSUE TITLE
filerouter seems to request page even on first load

### ISSUE THREAD

**Issue by thomashandorf** [layerJS/layerJS#52]
tested in local version of landing page:
when loading the page i get an error:
layerjs-0.4.0.js:3471 XMLHttpRequest cannot load file:///Users/handorf/dev/landingpage/index.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
apparently, the filerouter tries to load index.html even though this is already loaded

**Comment by kennytordeur** [comment]
Fixed it.

**Comment by thomashandorf** [comment]
the initial navigate call wasn’t just for the cache. I think it dealt with situations, where the url contains something like “…#frame2”, where frame2 is not the default frame (so it should immediately switch to frame2)

Can you please check if this functionality still works.

If not, is there a way to do navigate without a futile request from filerouter? 

By the way, the routing code needs some overhaul anyway. So if you don’t find a clear solution, just leave the issue open and we fix the filerouter later. (but the initial navigate as described before should work)

**Comment by thomashandorf** [comment]
this has been fixed.
