### ISSUE TITLE
other hash tags in URL break back button

### ISSUE THREAD

**Issue by thomashandorf** [layerJS/layerJS#58]
layers.org:

open one of the collapsible (“show full example”). This added something like #collapse4 in the url. Then go to impressum.html (via link at bottom) (transition occurs). Use back button. This will go back to the previous url (containing #collapse4) but will not transition back to index.html.

**Comment by kennytordeur** [comment]
corrected in commit 9b3f96821a659abdf578d6ec4bd501ed04f0a071
