### ISSUE TITLE
back button problem in hashrouter

### ISSUE THREAD

**Issue by thomashandorf** [layerJS/layerJS#70]
when using the back button going back to the original “no-hash” url the hash router fails

there is a check in the has router code which drops out if the hash is empty. however, it should go back the the default frames (of all layers i guess)

note: this probably worked previously since we had a filerouter that probably could handle this
note: the problem may get less severe if the history.state implementation would work completely. in window.onpopstate it is first checked if there is a state associated to the history. However this seems to be empty sometimes. (maybe for the first time after initialization?)

**Comment by kennytordeur** [comment]
Fixed in commit  a130629
