### ISSUE TITLE
Adapt page title when using filerouter

### ISSUE THREAD

**Issue by kennytordeur** [layerJS/layerJS#78]
When the framework is navigating between different webpages (FileRouter), the content of the page is adapted but the title of the page isn't.

Is would be nice is the title of the page is changed to the title of the page where we navigated to.

**Comment by thomashandorf** [comment]
Yes, that's definitely something that we could do. We would need to loop through the head of the new document and apply the changes also there. However, depending on the situation not all head tags should be overwritten/added. this still needs to be defined, but <title> should definitely be changed.
