### ISSUE TITLE
Layer JS site certificate is expired and other issues

### ISSUE THREAD

**Issue by lpercivalDEV** [layerJS/layerJS#82]
Apologies if this is not the proper spot/format for making someone aware of these issues - but I was not able to interact with the Layer JS website at all.

Issues I am seeing today:
- Layer JS Site Certificate is expired and gives a warning upon navigating to site.
- Also not able to access the Layer JS site menu or scroll down on site at all 
- No errors are given in the console when loading or clicking around on the Layer JS site
- The iframes I created using this library are now not loading properly

I have cleared my history, tried navigating to the site in Chrome and Firefox, and have double checked that my machine has the proper time/date (it does). I still get the same results above regardless of what browser I use.  

:(

Can someone confirm if the certificate issue, site navigation/scrolling issue, and my broken Layer JS iframes are tied together? 

![layerjs_cert_expired](https://user-images.githubusercontent.com/35902557/86490014-0222b700-bd34-11ea-9f5f-0cba159564a3.png)

![cert_expired](https://user-images.githubusercontent.com/35902557/86490264-c63c2180-bd34-11ea-8ad8-ca569b2bf61f.png)

**Comment by thomashandorf** [comment]
Hi Lilly,

Thanks for letting us know. I fixed the cert issue. Please check if the problems persist.

Thanks and best,
Thomas

**Comment by lpercivalDEV** [comment]
@thomashandorf Everything is fixed now! THANK YOU! :D
